apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: amoeeba-test   image: amoeeba/amoeeba-test    ports:
    - name: nodejs-port
      containerPort: 3000
