apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: amoeeba-test        image: amoeeba/amoeeba-test        ports:
        - name: nodejs-port
          containerPort: 3000
